### ISSUE TITLE
Unable to download the tool

### ISSUE THREAD

**Issue by VilainLab** [elnitskilab/MethylToSNP#1]
Hello, 

I am getting the following error while downloading the tool "**MethylToSNP**" tool errors "**ERROR: unable to collate and parse R files for package 'MethylToSNP**'". It seems to be an issue with the code in itself. pasting below the error in detail.
install_github("elnitskilab/MethylToSNP")
Downloading GitHub repo elnitskilab/MethylToSNP@master
Skipping 1 packages not available: minfi
Installing 3 packages: Ckmeans.1d.dp, Rdpack, gbRd
trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/Ckmeans.1d.dp_4.3.0.zip'
Content type 'application/zip' length 1137405 bytes (1.1 MB)
downloaded 1.1 MB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/Rdpack_0.11-1.zip'
Content type 'application/zip' length 956356 bytes (933 KB)
downloaded 933 KB

trying URL 'https://cran.rstudio.com/bin/windows/contrib/3.6/gbRd_0.4-11.zip'
Content type 'application/zip' length 44673 bytes (43 KB)
downloaded 43 KB

package 'Ckmeans.1d.dp' successfully unpacked and MD5 sums checked
package 'Rdpack' successfully unpacked and MD5 sums checked
package 'gbRd' successfully unpacked and MD5 sums checked

The downloaded binary packages are in
	C:\Users\Vilain Lab\AppData\Local\Temp\RtmpiGLSZf\downloaded_packages
√  checking for file 'C:\Users\Vilain Lab\AppData\Local\Temp\RtmpiGLSZf\remotes1c8c479d11d6\elnitskilab-MethylToSNP-36e4085/DESCRIPTION' ...
-  preparing 'MethylToSNP':
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
-  building 'MethylToSNP_0.99.0.tar.gz'
   
* installing *source* package 'MethylToSNP' ...
** using staged installation
** R
Error in parse(outFile) : 
  C:/Users/Vilain Lab/AppData/Local/Temp/RtmpmUs6Ni/R.INSTALL2dd84dd363b3/MethylToSNP/R/MethylToSNP.R:23:9: unexpected symbol
22: MethylToSNP <- function(data, gap.ratio = 0.75, gap.sum.ratio = 0.5, verbose=FALSE, outlier.sd = 3.0, SNP
23:         method
            ^
ERROR: unable to collate and parse R files for package 'MethylToSNP'
* removing 'C:/Program Files/R/R-3.6.2/library/MethylToSNP'
Error: Failed to install 'MethylToSNP' from GitHub:
  (converted from warning) installation of package 'C:/Users/VILAIN~1/AppData/Local/Temp/RtmpiGLSZf/file1c8c2aaa1cea/MethylToSNP_0.99.0.tar.gz' had non-zero exit status
Also while d/l it from bioconductor I get the following error.
"package 'MethylToSNP' is not available (for R version 3.6.2) "
Please advise.

Thanks, 
Surajit Bhattacharya

**Comment by neksa** [comment]
Hi Surajit,

I confirm the issue, will get it fixed asap and will follow up here. My apologies for the inconvenience.

Thanks, Alex

**Comment by neksa** [comment]
Hi Surajit, the installation issues have been fixed. Also, Bioconductor is now an optional dependency, so you should be able to install it in bare R.

Please try again:
`install_github("elnitskilab/MethylToSNP")`
