### ISSUE TITLE
Failed to run MethylToSNP

### ISSUE THREAD

**Issue by DolapoA** [elnitskilab/MethylToSNP#3]
**Description:**
I'm having problems running the `MethylToSNP` function, I'm not sure what the problem is precisely.

**Problem:**
```
ncol(myUSARC_RAW)
[1] 85

nrow(myUSARC_RAW)
[1] 866836

mySNPs <- MethylToSNP(myUSARC_RAW, SNP=SNPs.147CommonSingle)
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  : 
  row names contain missing values
```
**Some checks:**
I checked to see if there were any missing values:
```
anyNA(myUSARC_RAW)
[1] FALSE

anyNA(rownames(myUSARC_RAW))
[1] FALSE
```
I was wondering if you've come across this before?

**Comment by neksa** [comment]
I could not reproduce it, unfortunately. The error message is a generic data frame constructor error, which could only be triggered in the very end of the MethylToSNP code when results are reported as a `data.frame`. Running `traceback()` could help see the call stack and narrow it down. I have a couple of questions that could help me identify the issue.

Did it also happen without specifying the `SNP=` parameter?

And most importantly, what is the data type (class) of `myUSARC_RAW` ? 

I'm wondering if you will have any `NA` row names in `anyNA(rownames(getBeta(myUSARC_RAW)))`

I apologize for a late reply, I'm no longer working in the lab.
