### ISSUE TITLE
Non-zero exit status when installing

### ISSUE THREAD

**Issue by tlmendez** [elnitskilab/MethylToSNP#4]
Hello, 

I am having trouble when I try to install MethyltoSNP on RStudio. I get this error. 

I have tried manually installing but cannot get it to work. 

Error: (converted from warning) package 'Ckmeans.1d.dp' was built under R version 4.0.3
Execution halted
ERROR: lazy loading failed for package 'MethylToSNP'
* removing 'C:/Users/tm/Documents/R/win-library/4.0/MethylToSNP'
Error: Failed to install 'MethylToSNP' from GitHub:
  (converted from warning) installation of package ‘C:/Users/tm/AppData/Local/Temp/RtmpM7GkiI/file2220326e171d/MethylToSNP_0.99.0.tar.gz’ had non-zero exit status
In addition: Warning message:
package ‘usethis’ was built under R version 4.0.3 

Is there something I am doing that is hindering the installation?

Thanks

**Comment by neksa** [comment]
I don't have a windows machine to reproduce the environment. The error is odd, are other packages installing fine? Could you try installing Ckmeans.1d.dp package in Rstudio, and once it's installed repeating installation of methyl2snp.

Apologies for a late reply, I am no longer at the NIH

**Comment by tlmendez** [comment]
Thanks for the reply!

I tried re-installing Cmeans,1d,dp but I got the same error. 

I ended up using the code below and it worked.

library(devtools)
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
install_github("elnitskilab/MethylToSNP")

**Comment by neksa** [comment]
That's an interesting workaround, thanks for sharing
